server:
  port: 8090

springdoc:
  swagger-ui:
    use-root-path: true

spring:
  application:
    name: sample-application
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    username: root
    password: root
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sample-application-database
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true

logging:
  level:
    io.github.cnadjim: DEBUG
    org.springframework.context.support: ERROR
    org.mongodb: ERROR
    org.apache.kafka: ERROR
